// Run only against a disposable workspace: this test changes module/layout state and creates tasks.
const assert = require("node:assert/strict");
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || "playwright");
const baseURL = process.env.WORKBENCH_TEST_URL || "http://127.0.0.1:18086";
(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_PATH || undefined, args: ["--no-sandbox"] });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = [];
    page.on("pageerror", (error) => errors.push(error.message));
    await page.goto(baseURL);
    await page.getByRole("heading", { name: "总览", exact: true }).waitFor();
    await page.getByRole("region", { name: "待办概览" }).waitFor();
    await page.getByRole("region", { name: "投资" }).waitFor();
    await page.getByRole("button", { name: "配置总览", exact: true }).click();
    await page.getByRole("checkbox", { name: "待办概览", exact: true }).uncheck();
    await page.getByLabel("投资尺寸").selectOption("large");
    await page.getByRole("button", { name: "投资上移", exact: true }).click();
    await page.getByRole("button", { name: "保存布局", exact: true }).click();
    await page.getByRole("region", { name: "待办概览" }).waitFor({ state: "detached" });
    await page.reload();
    await page.getByRole("region", { name: "投资" }).waitFor();
    assert.match(await page.getByRole("region", { name: "投资" }).getAttribute("class"), /widget-large/);
    assert.equal(await page.getByRole("region", { name: "待办概览" }).count(), 0);
    await page.getByRole("link", { name: "待办", exact: true }).click();
    await page.getByRole("heading", { name: "待办", exact: true }).waitFor();
    // More than one page proves the UI consumes the backend cursor instead of silently truncating tasks.
    await page.evaluate(async () => {
      const { token } = await (await fetch("/api/auth/csrf")).json();
      for (let i = 0; i < 51; i++) {
        const response = await fetch("/api/modules/todo/tasks", { method: "POST", headers: { "Content-Type": "application/json", "X-CSRF-Token": token }, body: JSON.stringify({ title: `分页验证 ${i}` }) });
        if (!response.ok) throw new Error(`create failed: ${response.status}`);
      }
    });
    await page.reload();
    await page.getByRole("button", { name: "加载更多", exact: true }).click();
    await page.getByText("已加载 51 项", { exact: false }).waitFor();
    await page.goto(`${baseURL}/settings?tab=modules`);
    await page.getByRole("button", { name: "投资设置", exact: true }).click();
    assert.equal(await page.getByLabel("OAuth 回调地址", { exact: true }).inputValue(), baseURL.startsWith("https:") ? `${baseURL}/oauth/schwab` : "");
    await page.getByLabel("App Key", { exact: true }).fill("browser-test-key");
    await page.getByLabel("App Secret", { exact: true }).fill("browser-test-secret");
    await page.getByLabel("OAuth 回调地址", { exact: true }).fill(`${baseURL.replace(/^https:/, "http:")}/oauth/schwab`);
    const invalidCallback = page.waitForResponse(response => response.url() === `${baseURL}/api/modules/investment/schwab` && response.request().method() === "PUT");
    await page.getByRole("button", { name: "保存配置", exact: true }).click();
    assert.equal((await invalidCallback).status(), 400);
    await page.getByLabel("OAuth 回调地址", { exact: true }).fill(`${baseURL.replace(/^http:/, "https:")}/oauth/schwab`);
    const saved = page.waitForResponse(response => response.url() === `${baseURL}/api/modules/investment/schwab` && response.request().method() === "PUT");
    await page.getByRole("button", { name: "保存配置", exact: true }).click();
    assert.equal((await saved).status(), 200);
    await page.getByText("配置已保存，尚未完成 OAuth 授权。", { exact: true }).waitFor();
    assert.equal(await page.getByLabel("App Secret", { exact: true }).inputValue(), "");
    const config = await (await page.request.get(`${baseURL}/api/modules/investment/schwab`)).json();
    assert.equal(config.hasAppSecret, true);
    assert.equal(config.connected, false);
    assert(!JSON.stringify(config).includes("browser-test-secret"));
    await page.getByLabel("App Key", { exact: true }).fill("another-browser-key");
    const rejected = page.waitForResponse(response => response.url() === `${baseURL}/api/modules/investment/schwab` && response.request().method() === "PUT");
    await page.getByRole("button", { name: "保存配置", exact: true }).click();
    assert.equal((await rejected).status(), 400);
    await page.getByText("更换 App Key 时请重新填写 App Secret", { exact: true }).waitFor();
    assert(await page.getByRole("button", { name: "登录 Schwab", exact: true }).isDisabled());
    await page.getByRole("button", { name: "关闭模块设置", exact: true }).click();
    const moduleSwitch = page.getByRole("switch", { name: "投资", exact: true });
    await moduleSwitch.click();
    await page.waitForFunction(() => document.querySelector('[aria-label="投资"]')?.getAttribute("aria-checked") === "false");
    assert.equal(await page.getByRole("link", { name: "投资", exact: true }).count(), 0);
    assert.equal((await page.request.get(`${baseURL}/api/modules/investment/schwab`)).status(), 503);
    assert.equal((await page.request.get(`${baseURL}/investment/terminal`)).status(), 503);
    await page.goto(baseURL);
    await page.getByText("总览暂时没有卡片", { exact: true }).waitFor();
    await page.goto(`${baseURL}/settings?tab=modules`);
    await page.getByRole("switch", { name: "投资", exact: true }).click();
    await page.getByRole("link", { name: "投资", exact: true }).click();
    await page.getByRole("heading", { name: "投资", exact: true }).waitFor();
    await page.getByText("尚未连接 Schwab。", { exact: false }).waitFor();
    assert.equal(await page.getByRole("button", { name: "生成 AI 摘要", exact: true }).count(), 0);
    await page.goto(baseURL);
    await page.getByRole("button", { name: "配置总览", exact: true }).click();
    await page.getByRole("checkbox", { name: "待办概览", exact: true }).check();
    await page.getByLabel("待办概览尺寸").selectOption("small");
    await page.getByLabel("投资尺寸").selectOption("medium");
    await page.getByRole("button", { name: "保存布局", exact: true }).click();
    await page.getByRole("region", { name: "待办概览" }).waitFor();
    await page.getByRole("button", { name: "关闭配置", exact: true }).click();
    assert.deepEqual(await page.locator(".dashboard-widget").evaluateAll((nodes) => nodes.map((node) => node.getAttribute("aria-label"))), ["投资", "待办概览"]);
    await page.screenshot({ path: "/tmp/workbench-platform-dashboard.png", fullPage: true, animations: "disabled" });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.waitForFunction(() => document.querySelector(".workspace-sidebar")?.getBoundingClientRect().width <= 65);
    await page.screenshot({ path: "/tmp/workbench-platform-mobile.png", fullPage: true, animations: "disabled" });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, "mobile overflow");
    await page.goto(`${baseURL}/settings?tab=modules`);
    await page.getByRole("switch", { name: "待办", exact: true }).waitFor();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, "settings mobile overflow");
    await page.getByRole("button", { name: "投资设置", exact: true }).click();
    await page.getByLabel("App Key", { exact: true }).waitFor();
    assert.equal(await page.getByLabel("App Key", { exact: true }).inputValue(), "browser-test-key");
    assert.equal(await page.getByLabel("App Secret", { exact: true }).inputValue(), "");
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, "Schwab settings mobile overflow");
    await page.screenshot({ path: "/tmp/workbench-schwab-settings-mobile.png", fullPage: true, animations: "disabled" });
    assert.deepEqual(errors, []);
    console.log("PASS: module toggles and API gates, layout persistence, pagination, Schwab settings/secret redaction/credential validation, no demo controls, mobile layout; no page errors");
  } finally { await browser.close(); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
